apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app371
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/app371
    repoURL: https://github.com/gitops-workshop/load-test
    targetRevision: HEAD